### ISSUE TITLE
🐞 Infinite alert loop during gameover

### ISSUE THREAD

**Issue by PezCoder** [PezCoder/Mr.Snake#1]
When the game is over, the alert box saying "game over" shows up & it goes into an infinite loop.

Some hints:
- [x] Search for `game over` in javascript file to know where to start
- [ ] Try to understand the root cause of the issue by using debugger points
- [ ] Comment on this issue to discuss how you're going to fix it before creating a PR
- [ ] Create a PR with the fix

Look the repo for live link to play the game & contributing guidelines
https://github.com/PezCoder/Mr.Snake

**Comment by masquel** [comment]
Hey, @PezCoder. I'll try to solve it

**Comment by masquel** [comment]
@PezCoder you need to reset app state after alert was closed. See example of reseting of lives in #2 PR. You need to make an object with initial state and use it to reset after game is over.

**Comment by PezCoder** [comment]
Thank you for this, I'll review your pr in a moment.

**Comment by masquel** [comment]
@PezCoder previous PR has too much changes. See #3 PR for fast and easy fix
